### ISSUE TITLE
Break down by OS->Hostname->Distro

### ISSUE THREAD

**Issue by flowchartsman** [hypnoglow/dotbro#12]
It would be nice to have optional mappings/init/etc broken down by OS, then Hostname, then distro/version like the following JSON
```json
{
  "mappings": {
    "one": "two",
    "two": "three"
  },
  "init" : [
    "one",
    "two"
  ],
  "env" : {
    "linux" :{
      "mappings": {
        "three": "four"
      },
      "init" : [
        "three"
      ]
    }
  }
}
```

But, alas, TOML doesn't support arrays and tables at the same level unless they're written in a particular order.

```toml
#totally fine
bar = [
  "one",
  "two"
]

[foo]
one = "two"
three = "four"
```

```toml
#nope
[foo]
one = "two"
three = "four"

bar = [
  "one",
  "two"
]
```

YAML's cool with it, though:
```yaml
foo:
  one: two
  three: four
bar:
  - one
  - two
```

Kind of a big change, but it would dovetail nicely with init command substitutions. Opening issue to track.
